In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
tensor = torch.tensor(data)

In [4]:
tensor

tensor([[1, 2],
        [3, 4]])

In [8]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
rand_tensor = torch.randn(2, 3, 4)

In [29]:
print(rand_tensor)

tensor([[[-0.2149, -1.1309,  0.4767, -0.1179],
         [ 0.5555, -2.4821,  1.2919,  0.4058],
         [ 1.0496,  1.3812, -0.5521,  0.8489]],

        [[ 0.5541, -0.2799, -0.3901, -0.5425],
         [-0.0999, -0.6679, -0.8086,  0.4351],
         [-0.0672, -2.7523, -0.4177,  0.3040]]])


In [30]:
rand_tensor_reshaped = torch.reshape(rand_tensor, (2, 12))

In [31]:
rand_tensor_reshaped

tensor([[-0.2149, -1.1309,  0.4767, -0.1179,  0.5555, -2.4821,  1.2919,  0.4058,
          1.0496,  1.3812, -0.5521,  0.8489],
        [ 0.5541, -0.2799, -0.3901, -0.5425, -0.0999, -0.6679, -0.8086,  0.4351,
         -0.0672, -2.7523, -0.4177,  0.3040]])

In [32]:
torch.reshape(rand_tensor_reshaped, (2, 3, 4))

tensor([[[-0.2149, -1.1309,  0.4767, -0.1179],
         [ 0.5555, -2.4821,  1.2919,  0.4058],
         [ 1.0496,  1.3812, -0.5521,  0.8489]],

        [[ 0.5541, -0.2799, -0.3901, -0.5425],
         [-0.0999, -0.6679, -0.8086,  0.4351],
         [-0.0672, -2.7523, -0.4177,  0.3040]]])

In [35]:
type(torch.tensor([[1,2], [3,4]]))

torch.Tensor

In [36]:
rand_tensor.dtype

torch.float32

### Basic Operations

In [51]:
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[1], [2]])
m3 = torch.tensor([[1, 2], [1, 1]])

In [52]:
m1 + m3

tensor([[2, 4],
        [4, 5]])

In [53]:
m1 + m2

tensor([[2, 3],
        [5, 6]])

In [54]:
m1/m2

tensor([[1.0000, 2.0000],
        [1.5000, 2.0000]])

In [57]:
torch.matmul(m1, m3)

tensor([[ 3,  4],
        [ 7, 10]])

### Normalize a tensor to range [0, 1]

In [69]:
t1 = torch.rand((4, 4))

In [113]:
t1 = t1 + 1000
t1 *= t1
# t1 = torch.exp(t1)
t1.view(2,8)

tensor([[1.0078e+24, 1.0066e+24, 1.0040e+24, 1.0121e+24, 1.0091e+24, 1.0117e+24,
         1.0070e+24, 1.0090e+24],
        [1.0095e+24, 1.0111e+24, 1.0084e+24, 1.0057e+24, 1.0115e+24, 1.0066e+24,
         1.0109e+24, 1.0041e+24]])

In [73]:
t1_max = torch.max(t1)
t1_min = torch.min(t1)

In [74]:
t1 = (t1 - t1_min)/(t1_max - t1_min)

In [75]:
t1

tensor([[0.4675, 0.3177, 0.0000, 1.0000],
        [0.6392, 0.9571, 0.3715, 0.6251],
        [0.6783, 0.8813, 0.5491, 0.2071],
        [0.9277, 0.3194, 0.8619, 0.0102]])

### Compute column-wise mean and std of a 2D tensor.

In [76]:
t2 = torch.rand((3, 6))

In [77]:
t2

tensor([[0.4214, 0.3412, 0.0120, 0.4369, 0.8258, 0.5694],
        [0.7326, 0.8969, 0.8391, 0.0956, 0.6036, 0.8524],
        [0.7538, 0.5622, 0.6988, 0.4677, 0.9620, 0.3396]])

In [89]:
for i in range(t2.shape[0]):
    print(t2[i:i+1])

tensor([[0.4214, 0.3412, 0.0120, 0.4369, 0.8258, 0.5694]])
tensor([[0.7326, 0.8969, 0.8391, 0.0956, 0.6036, 0.8524]])
tensor([[0.7538, 0.5622, 0.6988, 0.4677, 0.9620, 0.3396]])


In [99]:
t2_col_means = [float(torch.mean(t2[:, i:i+1])) for i in range(t2.shape[1])]

In [100]:
t2_col_means

[0.6359184384346008,
 0.6001086831092834,
 0.516633927822113,
 0.3333914279937744,
 0.7971186637878418,
 0.5871386528015137]

In [108]:
t2_col_means = t2.mean(dim=0)
t2_col_stds  = t2.std(dim=0)

In [109]:
t2_col_means

tensor([0.6359, 0.6001, 0.5166, 0.3334, 0.7971, 0.5871])

In [110]:
t2_col_stds

tensor([0.1861, 0.2798, 0.4427, 0.2065, 0.1809, 0.2569])


### Take a [2, 3, 4] tensor and flatten to [2, 12], then reshape back.

In [101]:
t3 = torch.rand(2, 3, 4)

In [103]:
t3

tensor([[[0.0723, 0.3926, 0.2041, 0.4862],
         [0.9439, 0.3943, 0.9682, 0.6118],
         [0.4971, 0.6788, 0.2257, 0.9730]],

        [[0.1123, 0.1002, 0.8996, 0.3750],
         [0.8436, 0.6720, 0.2974, 0.5765],
         [0.7862, 0.3165, 0.1700, 0.2455]]])

In [105]:
t3.reshape(2, 12)

tensor([[0.0723, 0.3926, 0.2041, 0.4862, 0.9439, 0.3943, 0.9682, 0.6118, 0.4971,
         0.6788, 0.2257, 0.9730],
        [0.1123, 0.1002, 0.8996, 0.3750, 0.8436, 0.6720, 0.2974, 0.5765, 0.7862,
         0.3165, 0.1700, 0.2455]])

In [106]:
t3 = t3.reshape(2, 12)

In [107]:
t3.reshape(2, 3, 4)

tensor([[[0.0723, 0.3926, 0.2041, 0.4862],
         [0.9439, 0.3943, 0.9682, 0.6118],
         [0.4971, 0.6788, 0.2257, 0.9730]],

        [[0.1123, 0.1002, 0.8996, 0.3750],
         [0.8436, 0.6720, 0.2974, 0.5765],
         [0.7862, 0.3165, 0.1700, 0.2455]]])