# Autograd & Simple Gradient Descent

In [1]:
import torch

## 1. Autograd toy

In [2]:
t1 = torch.randn(2, 3, requires_grad=True)
t1

tensor([[-0.8268,  0.9732,  0.5528],
        [-1.6423, -0.7122, -0.8010]], requires_grad=True)

In [3]:
t2 = (t1**2).sum()

In [4]:
t2

tensor(5.7823, grad_fn=<SumBackward0>)

In [5]:
print(t2.backward())

None


In [6]:
print(t1.grad)

tensor([[-1.6536,  1.9463,  1.1057],
        [-3.2846, -1.4245, -1.6019]])


## 2. Manual Linear Regression

In [53]:
# Synthetic data
# true w=3, b=2
X = torch.randn(100, 1)
y = 3 * X + 2 + 0.001 * torch.randn(100, 1)

# y = w * X + b + noise

In [59]:
# init w and b for regression
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# linear regression loop:
iter = 5_000
alpha = 0.01

print("| Loss | w | b |")

while iter:
    iter -= 1
    y_pred = X@w + b
    
    y_pred = y_pred.reshape(100,1)
    
    loss = torch.mean((y - y_pred)**2)
    if iter%500 == 0:
        print(float(loss.data), float(w.data), float(b.data))
    
    loss.backward()
    
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    w.grad.zero_()
    b.grad.zero_()


| Loss | w | b |
9.200806516673765e-07 2.999845027923584 2.0000267028808594
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188


## 3. Use Optimizer

In [57]:
# init w and b for regression
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# linear regression loop:
iter = 5_000
alpha = 0.01

print("| Loss | w | b |")

optim = torch.optim.SGD([w,b], lr=alpha)

while iter:
    iter -= 1
    y_pred = X@w + b
    
    y_pred = y_pred.reshape(100,1)
    loss = torch.mean((y - y_pred)**2)
    if iter%500 == 0:
        print(float(loss.data), float(w.data), float(b.data))
    
    optim.zero_grad()
    loss.backward()
    optim.step()


| Loss | w | b |
8.922568213165505e-07 2.9999098777770996 2.0000998973846436
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188
8.826633006719931e-07 2.9999630451202393 2.0001754760742188


In [60]:
t3 = torch.randn(100,1)
t4 = torch.randn(1)

In [61]:
t3

tensor([[ 6.7419e-01],
        [-1.5038e+00],
        [ 5.6467e-01],
        [-1.8954e+00],
        [-1.0243e+00],
        [-2.6497e-01],
        [ 2.3893e-01],
        [ 4.1690e-01],
        [-2.3808e-01],
        [ 1.0237e+00],
        [-1.4052e+00],
        [-5.6753e-01],
        [-5.4989e-03],
        [-1.5866e+00],
        [ 1.9013e+00],
        [-1.0992e-01],
        [-8.5700e-01],
        [-4.3154e-01],
        [ 4.2440e-01],
        [-8.9557e-01],
        [-5.5457e-01],
        [ 4.3522e-01],
        [ 1.2140e+00],
        [-9.8813e-02],
        [-7.6449e-01],
        [ 1.2513e-01],
        [ 3.0284e-01],
        [-2.1663e+00],
        [-1.2177e+00],
        [-1.5609e+00],
        [ 1.7614e+00],
        [-6.2550e-01],
        [-2.1867e+00],
        [ 1.8600e-01],
        [-2.8195e-01],
        [-9.4885e-01],
        [-2.8469e-01],
        [-3.2033e-01],
        [-8.1374e-01],
        [ 2.8297e-01],
        [-2.0626e-03],
        [ 1.7990e+00],
        [ 3.8855e-01],
        [-9

In [62]:
t4

tensor([-0.0049])

In [63]:
t3+t4

tensor([[ 0.6693],
        [-1.5087],
        [ 0.5598],
        [-1.9003],
        [-1.0292],
        [-0.2699],
        [ 0.2340],
        [ 0.4120],
        [-0.2430],
        [ 1.0187],
        [-1.4101],
        [-0.5724],
        [-0.0104],
        [-1.5915],
        [ 1.8964],
        [-0.1148],
        [-0.8619],
        [-0.4364],
        [ 0.4195],
        [-0.9005],
        [-0.5595],
        [ 0.4303],
        [ 1.2091],
        [-0.1037],
        [-0.7694],
        [ 0.1202],
        [ 0.2979],
        [-2.1712],
        [-1.2226],
        [-1.5658],
        [ 1.7564],
        [-0.6304],
        [-2.1916],
        [ 0.1811],
        [-0.2869],
        [-0.9538],
        [-0.2896],
        [-0.3252],
        [-0.8186],
        [ 0.2781],
        [-0.0070],
        [ 1.7941],
        [ 0.3836],
        [-0.1039],
        [-1.4239],
        [ 1.2099],
        [ 1.2465],
        [ 1.6353],
        [ 1.3533],
        [-0.6799],
        [-0.6827],
        [ 0.0325],
        [-1.